//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Board.java
//  @ Date : 2023-04-03
//  @ Author : 
//
//
package tetris;
public class Board {
	public Cell[][] board;
	public int width;
	public int height;
	private Shape block;
	public Board(int height, int width) {
		board = new Cell[height][width];
		for (int i = 0; i < height; i++) {
			for (int j = 0; j < width; j++) {
				board[i][j] = new Cell('.'); //new Cell(); board[i][j].setTexture('.');
			}
		}
		this.height=height;
		this.width = width;
	}
	public void show() {
		for (int i = 0; i < board.length; i++) {
			for (int j = 0; j < board[i].length; j++) {
				System.out.printf("%c", board[i][j].getTexture());
			}
			System.out.println();
		}
	}
}
