//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 2023-04-03
//  @ Author : 
//
//


package tetris;

public class Cell {
	private char texture;

	public Cell(char texture){
		this.texture = texture;
	}
	public char getTexture(){
		return texture;
	};
	public void setTexture(char texture){
		this.texture = texture;
	}
}
